version: '3.8'

services:
  batch:
    container_name: batch-service
    image: 090188239653.dkr.ecr.ap-northeast-2.amazonaws.com/batch-service
    volumes:
      - /home/ubuntu/config/batch/application.yml:/config/batch/application.yml
    environment:
      - SPRING_CONFIG_LOCATION=file:/config/batch/application.yml
    ports:
      - "8087:8087"
    env_file:
      - /home/ubuntu/env/.env.batch
    networks:
      - backend

networks:
  backend:
    external: true